=== begert/ffhs_xml/aufgaben_1/modulliste.dtd
<!ENTITY % person.basecontent "name, vorname, adresse, geburtsdatum, ahv-nummer">
<!ENTITY % person.baseattr "geschlecht (m|w) #REQUIRED">

<!ELEMENT schule (modulliste, personen)>

<!ELEMENT modulliste (modul+)>

<!ELEMENT modul (modul-name, studiengang+)>
<!ATTLIST modul kuerzel CDATA #REQUIRED>
<!ELEMENT modul-name (#PCDATA)>
<!ELEMENT studiengang (#PCDATA)>

<!ELEMENT personen (dozent*, student*)>
<!ELEMENT dozent (%person.basecontent;, unterrichtet*)>
<!ATTLIST dozent %person.baseattr;>
<!ELEMENT student (%person.basecontent;, pruefungsnote*)>
<!ATTLIST student %person.baseattr;>

<!ELEMENT name (#PCDATA)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT geburtsdatum (#PCDATA)>
<!ELEMENT ahv-nummer (#PCDATA)>

<!ELEMENT unterrichtet (#PCDATA)>

<!ELEMENT pruefungsnote (#PCDATA)>
<!ATTLIST pruefungsnote modul CDATA #REQUIRED
                        datum NMTOKEN #REQUIRED>



<!--

Liste der Module
Jedes Modul besitzt einen Namen und ein Kürzel
Jedes Modul ist einem oder mehreren Studiengängen zugeordnet.
Listen der Studierenden und Dozierenden
Für Studierende und Dozierende sollten Name, Vorname, Adresse, Geburtsdatum, Geschlecht sowie AHV-Nummer erfasst werden.
Für die Dozierenden ist erfasst, welche Module sie unterrichten.
Für Studierende sind alle abgelegten Modulprüfungen mit Note und Datum erfasst
-->

=== begert/ffhs_xml/aufgaben_1/modulliste.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE schule SYSTEM "modulliste.dtd">

<schule>
    <modulliste>

        <modul kuerzel="m1">
            <modul-name>Modul One</modul-name>
            <studiengang>BSC INF</studiengang>
            <studiengang>BSC WI</studiengang>
        </modul>

        <modul kuerzel="m2">
            <modul-name>Modul Two</modul-name>
            <studiengang>BSC INF</studiengang>
            <studiengang>BSC WI</studiengang>
        </modul>

    </modulliste>

    <personen>
        <dozent geschlecht="m">
            <name>Dozent</name>
            <vorname>Hans</vorname>
            <adresse>xxx</adresse>
            <geburtsdatum>1.1.1970</geburtsdatum>
            <ahv-nummer>1.2.3.4.5</ahv-nummer>
            <unterrichtet>m1</unterrichtet>
            <unterrichtet>m2</unterrichtet>
        </dozent>
        <student geschlecht="m">
            <name>Student</name>
            <vorname>Hans</vorname>
            <adresse>xxx</adresse>
            <geburtsdatum>1.1.1970</geburtsdatum>
            <ahv-nummer>1.2.3.4.5</ahv-nummer>
            <pruefungsnote modul="m1" datum="13.01.2016">5</pruefungsnote>
            <pruefungsnote modul="m2" datum="13.01.2016">3</pruefungsnote>
        </student>
    </personen>
</schule>
