=== begert/ffhs_xml/aufgaben_1/schule.dtd
<!ENTITY % person.basecontent "name, vorname, adresse, geburtsdatum, ahv-nummer">
<!ENTITY % person.baseattr "geschlecht (m|w) #REQUIRED">

<!ELEMENT schule (studiengaenge, module, personen)>

<!ELEMENT studiengaenge (studiengang+)>
<!ELEMENT studiengang (#PCDATA)>

<!ATTLIST studiengang id ID #REQUIRED>

<!ELEMENT module (modul+)>

<!ELEMENT modul (#PCDATA)>
<!ATTLIST modul kuerzel ID #REQUIRED
                studiengang IDREFS #REQUIRED>
<!ELEMENT modul-name (#PCDATA)>

<!ELEMENT personen (dozent*, student*)>
<!ELEMENT dozent (%person.basecontent;)>
<!ATTLIST dozent %person.baseattr;
                 unterrichtet IDREFS #IMPLIED>
<!ELEMENT student (%person.basecontent;, pruefungsnote*)>
<!ATTLIST student %person.baseattr;>

<!ELEMENT name (#PCDATA)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT geburtsdatum (#PCDATA)>
<!ELEMENT ahv-nummer (#PCDATA)>

<!ELEMENT pruefungsnote (#PCDATA)>
<!ATTLIST pruefungsnote modul IDREF #REQUIRED
                        datum NMTOKEN #REQUIRED>

=== begert/ffhs_xml/aufgaben_1/schule.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE schule SYSTEM "schule.dtd">

<schule>

    <studiengaenge>
        <studiengang id="inf">BSC Informatik</studiengang>
        <studiengang id="wi">Bsc Wirtschaftsinformatik</studiengang>
    </studiengaenge>

    <module>
        <modul kuerzel="m1" studiengang="inf wi">Modul Eins</modul>
        <modul kuerzel="m2" studiengang="wi">Modul Zwei</modul>
    </module>

    <personen>
        <dozent geschlecht="m" unterrichtet="m1 m2">
            <name>Dozent</name>
            <vorname>Hans</vorname>
            <adresse>xxx</adresse>
            <geburtsdatum>1.1.1970</geburtsdatum>
            <ahv-nummer>1.2.3.4.5</ahv-nummer>
        </dozent>
        <student geschlecht="m">
            <name>Student</name>
            <vorname>Hans</vorname>
            <adresse>xxx</adresse>
            <geburtsdatum>1.1.1970</geburtsdatum>
            <ahv-nummer>1.2.3.4.5</ahv-nummer>
            <pruefungsnote modul="m1" datum="13.01.2016">5</pruefungsnote>
            <pruefungsnote modul="m2" datum="13.01.2016">3</pruefungsnote>
        </student>
    </personen>
</schule>
