=== begert/ffhs_xml/task_page_47/kapitel.dtd
<!ELEMENT buch (kapitel+)>
<!ELEMENT kapitel (absatz+)>
<!ELEMENT absatz (#PCDATA | wichtig | unwichtig)*>
<!ELEMENT wichtig (#PCDATA)>
<!ELEMENT unwichtig (#PCDATA)>

=== begert/ffhs_xml/task_page_47/kapitel.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE buch SYSTEM "kapitel.dtd">

<buch>
    <kapitel>
        <absatz>
            Dies ist ein Absatz
            mit etwas <wichtig>wichtigem</wichtig>
            und etwas <unwichtig>unwichtigem</unwichtig>
        </absatz>
        <absatz>
            Dies ist ein Absatz
            mit etwas <wichtig>wichtigem</wichtig>
            und nochmal etwas <wichtig>wichtigem</wichtig>
        </absatz>
    </kapitel>
    <kapitel>
        <!-- leerer absatz -->
        <absatz></absatz>
    </kapitel>
</buch>
