=== begert/ffhs_xml/aufgaben_2/schule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.my-schule.com"
           xmlns="http://www.my-schule.com">

    <xs:element name="schule">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="studiengaenge" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="studiengang" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="id" type="xs:ID" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="module" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modul" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="kuerzel" type="xs:ID" use="required"/>
                                            <xs:attribute name="studiengang" type="xs:IDREFS" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="personen" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dozent" type="dozentType" minOccurs="1" maxOccurs="unbounded" />
                            <xs:element name="student" type="studentType" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="personBaseType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="vorname" type="xs:string" />
            <xs:element name="adresse" type="xs:string" />
            <xs:element name="geburtsdatum" type="xs:date" />
            <xs:element name="ahv-nummer" type="ahvNummerType" />
        </xs:sequence>
        <xs:attribute name="geschlecht" type="geschlechtType" />
    </xs:complexType>

    <xs:complexType name="dozentType">
        <xs:complexContent>
            <xs:extension base="personBaseType">
                <xs:attribute name="unterrichtet" type="xs:IDREFS" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="studentType">
        <xs:complexContent>
            <xs:extension base="personBaseType">
                <xs:sequence>
                    <xs:element name="pruefungsnote" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="noteType">
                                    <xs:attribute type="xs:IDREF" name="modul" use="required"/>
                                    <xs:attribute type="xs:date" name="datum" use="required"/>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="noteType">
        <xs:restriction base="xs:decimal">
            <xs:maxInclusive value="6.0" />
            <xs:minInclusive value="1.0" />
            <xs:fractionDigits value="2" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="ahvNummerType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{3}\.\d{4}\.\d{4}\.\d{2}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="geschlechtType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="w" />
            <xs:enumeration value="m" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== begert/ffhs_xml/aufgaben_2/schule.xml
<?xml version="1.0" encoding="UTF-8" ?>

<mys:schule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:mys="http://www.my-schule.com"
        xsi:schemaLocation="http://www.my-schule.com schule.xsd">

    <studiengaenge>
        <studiengang id="inf">BSC Informatik</studiengang>
        <studiengang id="wi">Bsc Wirtschaftsinformatik</studiengang>
    </studiengaenge>

    <module>
        <modul kuerzel="m1" studiengang="inf wi">Modul Eins</modul>
        <modul kuerzel="m2" studiengang="wi">Modul Zwei</modul>
    </module>

    <personen>
        <dozent geschlecht="m" unterrichtet="m2">
            <name>Dozent</name>
            <vorname>Hans</vorname>
            <adresse>xxx</adresse>
            <geburtsdatum>1980-07-22</geburtsdatum>
            <ahv-nummer>123.1234.5678.99</ahv-nummer>
        </dozent>
        <student geschlecht="m">
            <name>Student</name>
            <vorname>Hans</vorname>
            <adresse>xxx</adresse>
            <geburtsdatum>1990-08-04</geburtsdatum>
            <ahv-nummer>123.1234.5678.99</ahv-nummer>
            <pruefungsnote modul="m1" datum="2016-01-13">5.25</pruefungsnote>
            <pruefungsnote modul="m2" datum="2016-12-01">6.0</pruefungsnote>
        </student>
    </personen>
</mys:schule>
