=== begert/ffhs_xml/mitschrift_2/contacts.dtd
<!ELEMENT CONTACTLIST (CONTACT+)>
<!ELEMENT CONTACT (NAME, ADDRESS?, PHONE*, MAIL)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT ADDRESS (#PCDATA)>
<!ELEMENT PHONE (#PCDATA)>
<!ELEMENT MAIL (#PCDATA)>

<!ATTLIST PHONE type CDATA #REQUIRED>

=== begert/ffhs_xml/mitschrift_2/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CONTACTLIST SYSTEM "contacts.dtd">
<CONTACTLIST>
    <CONTACT>
        <NAME>dkfjd</NAME>
        <ADDRESS>kdjfkdjf</ADDRESS>
        <PHONE type="mobile">dkfjk</PHONE>
        <PHONE type="private">dkfjk</PHONE>
        <MAIL>kdjfkdj</MAIL>
    </CONTACT>
    <CONTACT>
        <NAME>dkfjd</NAME>
        <ADDRESS>kdjfkdjf</ADDRESS>
        <PHONE type="office">dkfjk</PHONE>
        <PHONE type="fax">dkfjk</PHONE>
        <MAIL>kdjfkdj</MAIL>
    </CONTACT>
</CONTACTLIST>
