=== begert/ffhs_xml/mitschrift_2/test.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="contactlist">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="contact" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="phoneType">
        <xs:restriction>
            <xs:enumeration value="mobile" />
            <xs:enumeration value="private" />
            <xs:enumeration value="office" />
            <xs:enumeration value="fax" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="contact">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" minOccurs="1" />
                <xs:element name="address" type="xs:string" minOccurs="0" maxOccurs="1" />
                <xs:element name="phone" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="type" type="phoneType" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="mail" type="xs:string" minOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== begert/ffhs_xml/mitschrift_2/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<contactlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="test.xsd">
    <contact>
        <name>dkfjd</name>
        <address>kdjfkdjf</address>
        <phone type="mobile">dkfjk</phone>
        <phone type="private">dkfjk</phone>
        <mail>kdjfkdj</mail>
    </contact>
    <contact>
        <name>dkfjd</name>
        <address>kdjfkdjf</address>
        <phone type="office">dkfjk</phone>
        <phone type="fax">dkfjk</phone>
        <mail>kdjfkdj</mail>
    </contact>
</contactlist>
